### ISSUE TITLE
`match?` alias for `=~` in `StrongJSON::Type::Match`

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/strong_json#13]
Does it make sense to add `match?` alias for `=~`?

https://github.com/soutaro/strong_json/blob/faf4b464f2f56c4062a6febdb156e258a9efc228/lib/strong_json/type.rb#L5-L16

This idea is inspired by [`Regexp#match?`](http://ruby-doc.org/core-2.6.2/Regexp.html#method-i-match-3F) and [`Regexp#=~`](http://ruby-doc.org/core-2.6.2/Regexp.html#method-i-3D~).

In addition (it might be trivial), I think the alias can avoid warnings by RuboCop's [Performance/RegexpMatch](https://github.com/rubocop-hq/rubocop-performance/blob/master/manual/cops_performance.md#performanceregexpmatch) rule.

**Comment by soutaro** [comment]
I'm not very positive for adding another exact alias `match?` because it does not have any special meaning in Ruby, while I don't have strong reason to reject the idea. So, you can open a pull request.

**Comment by ybiquitous** [comment]
Thanks for the response! I see. 👍 
The idea does not make sense well, so I'll close this issue.

In the future, when it will be necessary for me, I may open a PR. 😅
