### ISSUE TITLE
I want `Object` type NOT ignore unknown attributes by default

### ISSUE THREAD

**Issue by yykamei** [soutaro/strong_json#16]
`Object` type ignores unknown attributes by default since version 1.0.0. But, I prefer the old behavior which prohibits any unknown keys by default. What do you think?

**Comment by soutaro** [comment]
Makes sense. 👍

**Comment by soutaro** [comment]
The expected behavior is:

1. When an unexpected attribute is given, StrongJSON raises an error.
2. When an ignored attribute is given, StrongJSON deletes the key-value from the object.

**Comment by soutaro** [comment]
Fixed in https://github.com/soutaro/strong_json/releases/tag/v2.0.0.

It rejects unknown attributes by default, and you can use `#ignore`/`#reject` methods to control the behavior.

**Comment by yykamei** [comment]
I confirmed! Thank you :+1:
