### ISSUE TITLE
Support integer type

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/strong_json#19]
Hi,

Do you have a plan to add `integer` as a new [base type](https://github.com/soutaro/strong_json#base-types)?

E.g.

```ruby
s = StrongJSON.new do
  let :unit_price, integer
end
```

Or is there some reasons not to have an `integer` type?

**Comment by soutaro** [comment]
Sounds good. 👍 https://github.com/soutaro/strong_json/pull/20

**Comment by ybiquitous** [comment]
Thanks a lot! 🎉
